bootstrap.servers=pkc-oxqxx9.us-east-1.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=66OWSOJP7VV72B3A
sasl.password=cfltbqLFG2CNsxbK6HtuyprdICu1IutQRT9qe14OerW8kFM2xCnUGKTF7XKVNL+Q